### ISSUE TITLE
As a tattoo artist (admin), I want to log in with my email address and password so that I can access the administrator website

### ISSUE THREAD

**Issue by gretron** [gretron/beatattoos#47]
### Tasks
- [x] Create user flow diagram
  - [x] Add user flow diagram to PRD
- [x] Create wireframe (optional)
  - [x] Add wireframe to SDD
- [x] Create mockup
  - [x] Add mockup to SDD
- [x] Create implementation
- [x] Create unit tests (optional)
- [x] Create integration tests
- [ ] Create end-to-end tests

### Acceptance Criteria
- [x] **Scenario**: Successful tattoo artist (admin) login with valid account credentials
  - **Given** that the tattoo artist is on the Landing page
  - **When** the tattoo artist clicks on the "Log In" button
  - **Then** the Log In page opens
  - **When** the tattoo artist enters valid account credentials
  - **Then** the system logs in the tattoo artist
  - **And** the Home page opens
- [x] **Scenario**: Unsuccessful tattoo artist (admin) login with invalid account credentials
  - **Given** that the tattoo artist is on the Login page
  - **When** the tattoo artist enters and submits invalid account credentials
  - **Then** the system validates the account credentials
  - **And** notifies the tattoo artist that the account credentials are invalid
