### ISSUE TITLE
Setup the base project for the web application

### ISSUE THREAD

**Issue by gretron** [gretron/beatattoos#74]
**Tasks**
- [x] Create the base software architecture diagram in FigJam
- [x] Add link to the software architecture diagram in the Software Design Document
- [x] Setup the project structure based on the architecture diagram
