### ISSUE TITLE
As a tattoo artist (admin), I want to register with my email address and password during the initial setup so that I can create an account with access to the admin website

### ISSUE THREAD

**Issue by gretron** [gretron/beatattoos#79]
### Tasks
- [x] Create user flow diagram
  - [x] Add user flow diagram to PRD
- [x] Create wireframe (optional)
  - [x] Add wireframe to SDD
- [x] Create mockup
  - [x]  Add mockup to SDD

### Acceptance Criteria
- [x] **Scenario**: Successful tattoo artist admin onboarding with valid admin token and account credentials
  - **Given** that the tattoo artist is on the Landing page
  - **When** the tattoo artist clicks on the "First Time Use" button
  - **Then** the Admin Token page opens
  - **When** the tattoo artist enters a valid admin token
  - **Then** the Register page opens
  - **When** the tattoo artist enters valid account credentials
  - **Then** the system creates the admin account
  - **And** the Login page opens
- [x] **Scenario**: Unsuccessful tattoo artist admin onboarding with invalid admin token
  - **Given** that the tattoo artist is on the Admin Token page
  - **When** the tattoo artist enters and submits a invalid admin token
  - **Then** the system validates the admin token
  - **And** notifies the tattoo artist that the admin token is invalid
- [x] **Scenario**: Unsuccessful tattoo artist admin onboarding with invalid account credentials
  - **Given** that the tattoo artist is on the Register page
  - **When** the tattoo artist enters and submits invalid account credentials
  - **Then** the system validates the account credentials
  - **And** notifies the tattoo artist that the account credentials are invalid
