### ISSUE TITLE
As a tattoo artist (admin), I want to create client accounts so that I can make accounts for in-person clients

### ISSUE THREAD

**Issue by gretron** [gretron/beatattoos#96]
### Tasks
- [x] Create user flow diagram
  - [x] Add user flow diagram to PRD
- [x] Create wireframe (optional)
  - [x] Add wireframe to SDD
- [x] Create mockup
  - [x]  Add mockup to SDD
- [x] Create implementation
- [x] Create unit tests (optional)
- [x] Create integration tests
- [x] Create end-to-end tests

### Acceptance Criteria
- [x] **Scenario**: Successful client account creation
  - **Given** that the tattoo artist is on the Client List page
  - **When** the tattoo artist clicks on the New Client button
  - **Then** the Create Client page opens
  - **When** the tattoo artist enters valid client credentials
  - **And** clicks the Create button
  - **Then** the system creates the client account
  - **And** the Client page with the new client account information opens
- [x] **Scenario**: Unsuccessful client account creation with existing email
  - **Given** that the tattoo artist is on the Client List page
  - **When** the tattoo artist clicks on the New Client button
  - **Then** the Create Client page opens
  - **When** the tattoo artist enters valid client credentials including existing email
  - **And** clicks the Create button
  - **Then** the system validates the new client credentials
  - **And** notifies the tattoo artist that the email address is already in use
- [x] **Scenario**: Unsuccessful client account creation with invalid credentials
  - **Given** that the tattoo artist is on the Client List page
  - **When** the tattoo artist clicks on the New Client button
  - **Then** the Create Client page opens
  - **When** the tattoo artist enters invalid client credentials
  - **And** clicks the Create button
  - **Then** the system validates the new client credentials
  - **And** notifies the tattoo artist that the client credentials are invalid
