### ISSUE TITLE
As a tattoo artist (admin), I want to view client accounts so that I can be aware of client information

### ISSUE THREAD

**Issue by gretron** [gretron/beatattoos#98]
### Tasks
- [x] Create user flow diagram
  - [x] Add user flow diagram to PRD
- [x] Create wireframe (optional)
  - [x] Add wireframe to SDD
- [x] Create mockup
  - [x]  Add mockup to SDD
- [x] Create implementation
- [x] Create unit tests (optional)
- [x] Create integration tests
- [x] Create end-to-end tests

### Acceptance Criteria
- [x] **Scenario**: View client account details
  - **Given** that the tattoo artist is on the client list page
  - **When** the tattoo artist clicks on a client list item
  - **Then** the client details page opens
  - **And** client details are displayed
